### ISSUE TITLE
[Document] 유사 프로그램 분석

### ISSUE THREAD

**Issue by finite2030** [ssg-240304-java2/final-bidssgket#1]
## 🔖 Objective
유사 프로그램을 분석하여 발표한다.

## Tasks
- [x] 다양한 유사 프로그램 분석을 통해 프로젝트를 구상한다.
- [x] 경매 시스템을 분석하여 경매에 대해 이해한다.
- [x] 중고 거래 시스템을 분석하여 중고 거래에 대해 이해한다.
- [x] 회원 신용도 시스템을 분석하여 회원 등급에 대해 이해한다.

## Deadline
- 기한: 2024-7-18

## Reference
- CREAM
- 솔드아웃
- 당근
- 번개장터
- eBay
