### ISSUE TITLE
[Feature/상품] 시세 조회

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#12]
## 🍪 Description
상품의 시세를 조회하여 출력합니다.

## 🍪 To-Do
- [ ] 상품의 시세 조회
- [ ] 상품의 최고,최소 가격 출력
- [ ] 상품의 평균 가격 출력

## 🍪 ETC
- 차트 형태로 시세를 출력하기

## 🍪 Related issues
연관된 이슈번호: #이슈번호
