### ISSUE TITLE
[Feature/상품] 상품 조회

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#13]
## 🍪 Description
상품을 카테고리별로 조회하여 출력한다.

## 🍪 To-Do
- [ ] 상품을 조회하여 출력함
- [ ] 카테고리별로 상품을 조회함
- [ ] 상품을 최신등록순으로 정리함

## 🍪 ETC
- 카테고리별로 조회할 때만 최신등록순으로 정리한다.

## 🍪 Related issues
연관된 이슈번호: #이슈번호
