### ISSUE TITLE
[Feature/상품] 상품 검색

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#14]
## 🍪 Description
상품을 검색하여 출력합니다.

## 🍪 To-Do
- [ ] 검색으로 상품 조회
- [ ] 검색어와 동일한 제목을 가진 상품 출력
- [ ] 내용 안에 동일한 단어가 있는 상품 출력

## 🍪 ETC
- 내용안에 동일한 단어가 일치하는 확인한다.

## 🍪 Related issues
연관된 이슈번호: #이슈번호
