### ISSUE TITLE
[ Feature/UI ] UI 개선 사항

### ISSUE THREAD

**Issue by yujin4sth00** [ssg-240304-java2/final-bidssgket#140]
## 🍪 Description
테스트 케이스를 작성하고, 기능을 점검하면서 조언을 통해 개선해야 할 UI

## 🍪 To-Do
- [ ] 경매 입찰 등록 시 설명
- [ ] 버튼 색상 변경
- [ ] 타이머 기능 활성화시키기

## 🍪 ETC
기타사항

## 🍪 Related issues
연관된 이슈번호: #이슈번호
