### ISSUE TITLE
회원가입 #18

### ISSUE THREAD

**Issue by elliaaa** [ssg-240304-java2/final-bidssgket#18]
## 🍪 Description
사용자는 비스킷 중고거래 경매 사이트를 이용하기 위해 회원가입을 할 수 있다.

## 🍪 To-Do
- [ ] 사용자는 아이디, 비밀번호,닉네임, 휴대폰 번호, 주소와 상세주소를 입력해서 회원가입이 가능하다.
- [ ] 중복된 아이디는 사용이 불가하다.
- [ ] 필수적으로 작성해야 하는 부분은 주소를 제외한 나머지 정보들이다. (유효성 검사 필요.)

## 🍪 ETC
기타사항

## 🍪 Related issues
연관된 이슈번호: #이슈번호
