### ISSUE TITLE
[Document] DDD 설계

### ISSUE THREAD

**Issue by yujin4sth00** [ssg-240304-java2/final-bidssgket#2]
## 🔖 Objective
중고 거래 경매 사이트에 대한 도메인 별 설계

## Tasks
- [x] 필요 기능 이벤트 스토밍
- [x] 도메인 별 분류 및 이벤트, 외부 API, 정책, 어그리게잇, 커맨드 작성
- [x] 도메인 ( 상품, 경매, 즉시 구매, 주문, 회원, 결제/ 관리자, 사용자)

## Deadline
- 기한: 2024-07-28

## Reference
https://miro.com/app/board/uXjVKwrafQM=/
