### ISSUE TITLE
[Feature / 번개 경매] 번개 경매

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#21]
## 🍪 Description
번개 경매는 기존 경매와 달리 입찰을 1회만 할 수 있으며 수정,취소가 불가능하다

## 🍪 To-Do
- [ ] 경매 기간 시간 단위로 설정
- [ ] 경매 입찰 내역 숨기기
- [ ] 경매 기간 종료 후 입찰 내역 공개

## 🍪 ETC
- 번개 경매는 시간단위 기간을 설정하고 입찰이 수정,취소가 불가능하다 

## 🍪 Related issues
연관된 이슈번호: #이슈번호
