### ISSUE TITLE
[Feature/경매] 경매 상품 조회

### ISSUE THREAD

**Issue by yujin4sth00** [ssg-240304-java2/final-bidssgket#23]
## 🍪 Description
경매 상품 리스트를 조회

## 🍪 To-Do
- [ ] 경매 상품 전체 조회
- [ ] 경매 상품 검색

## 🍪 ETC
- [ ] 경매 마감 임박 순 정렬

## 🍪 Related issues
연관된 이슈번호: #이슈번호
