### ISSUE TITLE
[Feature/경매] 유찰된 상품 처리

### ISSUE THREAD

**Issue by yujin4sth00** [ssg-240304-java2/final-bidssgket#28]
## 🍪 Description
유찰된 상품에 대해 판매자는 판매 상태 지정 가능

## 🍪 To-Do
- [x] 유찰된 상품에 대해 판매자는 경매 재개
- [x] 경매 재개 시 상품 판매글 및 경매 기간 수정 가능
- [x] 유찰된 상품에 대해 판매자는 판매 취소

## 🍪 ETC
기타사항

## 🍪 Related issues
연관된 이슈번호: #104 
#102
