### ISSUE TITLE
[Feature/회원]리뷰 등록하기

### ISSUE THREAD

**Issue by elliaaa** [ssg-240304-java2/final-bidssgket#38]
## 🍪 Description
판매자와 구매자는 서로에 대한 리뷰를 남길 수 있다.

## 🍪 To-Do
- [ ] 판매자는 구매 상품에 대한 만족도는 별점으로 판매자에 대한 만족도는 1-100사이의 점수로 리뷰를 남길 수 있다.
- [ ]판매자는 구매자에 대한 리뷰를 남길 수 있다.
- [ ] 판매자와 구매자 모두 코멘트를 남길 수 있다.

## 🍪 ETC
기타사항

## 🍪 Related issues
연관된 이슈번호: #이슈번호
