### ISSUE TITLE
[Document] NCP 서버 CI/CD 구축 및 index 페이지 연결

### ISSUE THREAD

**Issue by finite2030** [ssg-240304-java2/final-bidssgket#5]
## 🔖 Objective
Naver Cloud Platform에 서버 CI/CD 구축하고 index 페이지를 연결한다.

## 🔖 Tasks
- [ ] NCP에 web 서버를 구축한다.
- [ ] NCP에 db 서버를 구축한다.
- [ ] NCP에 파일 서버를 구축한다.
- [ ] NCP web 서버에 index 페이지를 연결한다.

## 🔖 Deadline
이 기획 문서와 관련된 작업의 기한을 명시해 주세요.
- 기한: 2024-7-25
