### ISSUE TITLE
[Document] 기능 요구사항 명세서

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#71]
## 🔖 Objective
각기능의 요구사항 명세서를 작성합니다.

## 🔖 Tasks
- [x] 기능별 요구사항 정리
- [x] 사용자별 기능 요구사항 정리
- [x] 요구사항 명세서 작성

## 🔖 Deadline
이 기획 문서와 관련된 작업의 기한을 명시해 주세요.
- 기한: 2024-07-29
