### ISSUE TITLE
[Document] 엔티티 구성 및 테이블 생성

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/final-bidssgket#72]
## 🔖 Objective
엔티티를 구성하고 테이블을 생성합니다.

## 🔖 Tasks
- [x] 엔티티 구성
- [x] 엔티티 관계 정의
- [x] 엔티티 칼럼명 정리
- [x] 엔티티 관계 최종 확인
- [x] TestDB에 테이블 생성

## 🔖 Deadline
이 기획 문서와 관련된 작업의 기한을 명시해 주세요.
- 기한: 2024-08-04
